parameters:
  # Environment Name, needs to match a file in
  - name: "environmentName"
    type: string
  - name: helmfileDirectory
    type: string
  - name: "displayPrefix"
    type: string
    default: "App"
  - name: pregenerateSteps
    type: stepList
    default: []
  - name: "helmfileVersion"
    type: string
    default: "0.162.0"

steps:
  - ${{ parameters.pregenerateSteps }}
  - script: |
      curl -L https://github.com/helmfile/helmfile/releases/download/v{{ parameters.helmfileVersion }}/helmfile_{{ parameters.helmfileVersion }}_linux_amd64.tar.gz > $(Agent.TempDirectory)/helmfile.tar.gz
      tar -xvf $(Agent.TempDirectory)/helmfile.tar.gz -C $(Agent.TempDirectory)
      chmod +x $(Agent.TempDirectory)/helmfile
    displayName: ${{ parameters.displayPrefix }} - Install Helmfile
  - script: |
      cd ${{ parameters.helmfileDirectory }}
      $(Agent.TempDirectory)/helmfile repos --environment ${{ parameters.environmentName }}
    displayName: ${{ parameters.displayPrefix }} - Add Dependencies
  - script: |
      cd ${{ parameters.helmfileDirectory }}
      rm -Rf $(Build.ArtifactStagingDirectory)/output/${{ parameters.environmentName }}
      $(Agent.TempDirectory)/helmfile --environment ${{ parameters.environmentName }} template --output-dir-template "$(Build.ArtifactStagingDirectory)/output/{{ .Release.Namespace }}"
    displayName: ${{ parameters.displayPrefix }} - Generate Output Environments
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "$(Build.ArtifactStagingDirectory)/output/"
      artifactName: "${{ parameters.environmentName }}"
      artifactType: pipeline
