parameters:
  # Gitversion
  - name: gitVersionSpec
    type: string
    default: "6.0.x"

  # API Build Parameters
  - name: publishProject
    type: string
  - name: buildProject
    type: string
  - name: netCoreVersion
    type: string
    default: "6.x"
  - name: buildConfiguration
    type: string
    default: Release

  - name: externalFeedCredentials
    type: string
    default: "SpydersoftDevelop"

  # API Test Settings
  - name: executeTests
    type: boolean
    default: false
  - name: testProjects
    type: string
    default: "**/*tests/*.csproj"

  # API Sonarqube Settings
  - name: executeSonar
    type: boolean
    default: false
  - name: sonarEndpointName
    type: string
    default: ""
  - name: sonarProjectKey
    type: string
    default: ""
  - name: sonarProjectName
    type: string
    default: ""
  - name: useSonarCloud
    type: boolean
    default: false
  - name: sonarCloudOrganization
    type: string
    default: ""
  - name: sonarExtraProperties
    type: string
    default: ""

  # Build Artifact Settings
  - name: artifactName
    type: string

  # Docker Settings
  - name: buildAndPublishDockerImage
    type: boolean
    default: false
  - name: artifactZipName
    type: string
  - name: dockerImageName
    type: string
  - name: containerRegistryName
    type: string
    default: proget_docker
  - name: dockerFilePath
    type: string
    default: Dockerfile

  # Helmfile Config Settings
  - name: updateHelmConfig
    type: boolean
    default: false
  - name: helmfileRepoName
    type: string
  - name: imageTagVariableName
    type: string

  # Hooks
  - name: prebuildSteps
    type: stepList
    default: []
  - name: preTestSteps
    type: stepList
    default: []
  - name: setupSteps
    type: stepList
    default: []

variables:
  - name: DOCKER_BUILDKIT
    value: 1

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        workspace:
          clean: all
        pool:
          name: Default
          demands: agent.os -equals Linux
        steps:
          - checkout: self
            fetchDepth: 0
            clean: true
            persistCredentials: true

          - ${{ parameters.setupSteps }}

          - task: gitversion/setup@3
            displayName: Setup GitVersion on Agent
            inputs:
              versionSpec: ${{ parameters.gitVersionSpec }}
          - task: gitversion/execute@3
            displayName: Execute GitVersion to update build number

          - template: ../../step_collections/dotnet-api-build-steps/v1.yml
            parameters:
              buildProject: ${{ parameters.buildProject }}
              publishProject: ${{ parameters.publishProject }}
              netCoreVersion: ${{ parameters.netCoreVersion }}
              buildConfiguration: ${{ parameters.buildConfiguration }}
              externalFeedCredentials: ${{ parameters.externalFeedCredentials }}
              prebuildSteps: ${{ parameters.prebuildSteps }}
              preTestSteps: ${{ parameters.preTestSteps }}
              executeSonar: ${{ parameters.executeSonar }}
              sonarEndpointName: ${{ parameters.sonarEndpointName }}
              sonarProjectKey: ${{ parameters.sonarProjectKey }}
              sonarProjectName: ${{ parameters.sonarProjectName }}
              executeTests: ${{ parameters.executeTests }}
              testProjects: ${{ parameters.testProjects }}
              useSonarCloud: ${{ parameters.useSonarCloud }}
              sonarCloudOrganization: ${{ parameters.sonarCloudOrganization }}
              sonarExtraProperties: ${{ parameters.sonarExtraProperties }}
          # this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your pipeline.
          - publish: "$(Build.ArtifactStagingDirectory)"
            artifact: "${{ parameters.artifactName }}"

  - ${{ if eq(parameters.buildAndPublishDockerImage, true) }}:
      - stage: docker_publish
        displayName: Create Docker Image
        jobs:
          - template: ../../jobs/build-docker-image/v1.yml
            parameters:
              dockerImageName: ${{ parameters.dockerImageName}}
              containerRegistryName: ${{ parameters.containerRegistryName }}
              artifactName: "${{ parameters.artifactName }}"
              artifactZipName: ${{ parameters.artifactZipName }}
              dockerFilePath: ${{ parameters.dockerFilePath }}

  - ${{ if eq(parameters.updateHelmConfig, true) }}:
      - stage: updateHelmConfig
        displayName: Update Helm Config Repository
        dependsOn:
          - docker_publish
        jobs:
          - job: updateHelmConfigJob
            pool:
              name: Default
            workspace:
              clean: all
            steps:
              - template: ../../step_collections/process-cicd-script/v1.yml
                parameters:
                  repositoryResource: ${{ parameters.helmfileRepoName }}
                  branchName: $(Build.SourceBranch)
                  tagsCollection: ${{ parameters.imageTagVariableName }}=$(build.buildnumber)
                  commitMessage: Updated ${{ parameters.imageTagVariableName }} to $(build.buildnumber)
