parameters:
  - name: kubernetesConnectionName
    type: string
  - name: environmentName
    type: string
  - name: namespace
    type: string
  - name: helmfileDirectory
    default: './'
    type: string
  - name: argoRepoName
    type: string
  - name: argoBaseDir
    type: string
    default: apps

stages:
- stage: generate_commit_manifest_${{ parameters.environmentName }}
  displayName: Deploy To ${{ parameters.environmentName }} Environment
  jobs:
  - job: generate_manifests_${{ parameters.environmentName }}
    pool:
      name: Default
    steps:
    - template: ../../publish/helmfileconfig/steps-helmfile-template/steps-helmfile-template-v1.yml
      parameters:
        kubernetesConnectionName: "${{ parameters.kubernetesConnectionName }}"
        environmentName: "${{ parameters.environmentName }}"
        namespace: "${{ parameters.namespace }}"
        helmfileDirectory: "${{ parameters.helmfileDirectory }}"
  - job: commit_changes_${{ parameters.environmentName }}
    dependsOn:
    - generate_manifests_${{ parameters.environmentName }}
    pool:
      name: Default
    steps:
    - template: ../../publish/helmfileconfig/steps-update-argorepo/steps-update-argorepo-v1.yml@templates
      parameters:
        repositoryResource: "${{ parameters.argoRepoName }}"
        artifactName: "${{ parameters.environmentName }}"
        commitMessage: "${{ parameters.environmentName }} - Update $(Build.BuildNumber)"
        argoBaseDir: "${{ parameters.argoBaseDir }}"