parameters:
  - name: environmentName
    type: string
  - name: helmfileDirectory
    default: "./"
    type: string
  - name: argoRepoName
    type: string
  - name: argoBaseDir
    type: string
    default: apps
  - name: pregenerateSteps
    type: stepList
    default: []
  - name: "helmfileVersion"
    type: string
    default: "0.162.0"

stages:
  - stage: generate_commit_manifest_${{ parameters.environmentName }}
    displayName: Deploy To ${{ parameters.environmentName }} Environment
    jobs:
      - deployment: deploy_marker_${{ parameters.environmentName }}
        displayName: Deployment Step
        environment: ${{ parameters.environmentName }}
        pool:
          name: Default
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Deploying to ${{ parameters.environmentName }}"
      - job: generate_manifests_${{ parameters.environmentName }}
        pool:
          name: Default
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
          - template: ../../step_collections/helmfile-template/v1.yml
            parameters:
              environmentName: "${{ parameters.environmentName }}"
              helmfileDirectory: "${{ parameters.helmfileDirectory }}"
              pregenerateSteps: ${{ parameters.pregenerateSteps }}
              helmfileVersion: ${{ parameters.helmfileVersion }}
      - job: commit_changes_${{ parameters.environmentName }}
        dependsOn:
          - generate_manifests_${{ parameters.environmentName }}
        pool:
          name: Default
        steps:
          - template: ../../step_collections/commit-to-gitops-repo/v1.yml@templates
            parameters:
              repositoryResource: "${{ parameters.argoRepoName }}"
              artifactName: "${{ parameters.environmentName }}"
              commitMessage: "${{ parameters.environmentName }} - Update $(Build.BuildNumber)"
              argoBaseDir: "${{ parameters.argoBaseDir }}"
