parameters:
  - name: kubernetesConnectionName
    type: string
  - name: environmentName
    type: string
  - name: namespace
    type: string
  - name: helmfileDirectory
    default: "./"
    type: string
  - name: argoRepoName
    type: string
  - name: argoBaseDir
    type: string
    default: apps
  - name: pre_generate_steps
    type: stepList
    default: []

stages:
  - stage: generate_commit_manifest_${{ parameters.environmentName }}
    displayName: Deploy To ${{ parameters.environmentName }} Environment
    jobs:
      - deployment: deploy_marker_${{ parameters.environmentName }}
        displayName: Deployment Step
        environment: ${{ parameters.environmentName }}
        pool:
          name: Default
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Deploying to ${{ parameters.environmentName }}"
      - job: generate_manifests_${{ parameters.environmentName }}
        pool:
          name: Default
        steps:
          - template: ../../step_collections/helmfile-template/v1.yml
            parameters:
              kubernetesConnectionName: "${{ parameters.kubernetesConnectionName }}"
              environmentName: "${{ parameters.environmentName }}"
              namespace: "${{ parameters.namespace }}"
              helmfileDirectory: "${{ parameters.helmfileDirectory }}"
              pre_generate_steps: ${{ parameters.pre_generate_steps }}
      - job: commit_changes_${{ parameters.environmentName }}
        dependsOn:
          - generate_manifests_${{ parameters.environmentName }}
        pool:
          name: Default
        steps:
          - template: ../../step_collections/commit-to-gitops-repov1.yml@templates
            parameters:
              repositoryResource: "${{ parameters.argoRepoName }}"
              artifactName: "${{ parameters.environmentName }}"
              commitMessage: "${{ parameters.environmentName }} - Update $(Build.BuildNumber)"
              argoBaseDir: "${{ parameters.argoBaseDir }}"
