parameters:
  - name: publishProject
    type: string
  - name: buildProject
    type: string
  - name: artifactName
    type: string
  - name: artifactZipName
    type: string
  - name: dockerImageFileName
    type: string
  - name: dockerImageName
    type: string
  - name: imageTagVariableName
    type: string
  - name: helmfileRepoName
    type: string

  - name: netCoreVersion
    type: string
    default: "6.0.x"
  - name: containerRegistryName
    type: string
    default: proget_docker
  - name: containerRegistryUrl
    type: string
    default: proget.mattgerega.com
  - name: buildConfiguration
    type: string
    default: Release
  - name: prebuildSteps
    type: stepList
    default: []
  - name: preTestSteps
    type: stepList
    default: []
  - name: execute_sonar
    type: boolean
    default: false
  - name: sonar_endpoint_name
    type: string
  - name: sonar_project_key
    type: string
  - name: sonar_project_name
    type: string
    default: ""
  - name: execute_tests
    type: boolean
    default: false
  - name: use_sonarcloud
    type: boolean
    default: false
  - name: sonar_cloud_organization
    type: string
    default: ""
  - name: test_projects
    type: string
    default: "**/*tests/*.csproj"
variables:
  - name: DOCKER_BUILDKIT
    value: 1

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        workspace:
          clean: all
        pool:
          name: Default
          demands: agent.os -equals Linux
        steps:
          - checkout: self
            fetchDepth: 0
            clean: true
          - task: gitversion/setup@0
            displayName: Setup GitVersion on Agent
            inputs:
              versionSpec: "5.x"
          - task: gitversion/execute@0
            displayName: Execute GitVersion to update build number

          - template: ../../step_collections/dotnet-api-build-steps/v1.yml
            parameters:
              buildProject: ${{ parameters.buildProject }}
              publishProject: ${{ parameters.publishProject }}
              netCoreVersion: ${{ parameters.netCoreVersion }}
              buildConfiguration: ${{ parameters.buildConfiguration }}
              prebuildSteps: ${{ parameters.prebuildSteps }}
              preTestSteps: ${{ parameters.preTestSteps }}
              executeSonar: ${{ parameters.execute_sonar }}
              sonarEndpointName: ${{ parameters.sonar_endpoint_name }}
              sonarProjectKey: ${{ parameters.sonar_project_key }}
              sonarProjectName: ${{ parameters.sonar_project_name }}
              executeTests: ${{ parameters.execute_tests }}
              testProjects: ${{ parameters.test_projects }}
              useSonarCloud: ${{ parameters.use_sonarcloud }}
              sonarCloudOrganization: ${{ parameters.sonar_cloud_organization }}
          # this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your pipeline.
          - publish: "$(Build.ArtifactStagingDirectory)"
            artifact: "${{ parameters.artifactName }}"

  - stage: docker_publish
    displayName: Create Docker Image
    jobs:
      - template: ../../jobs/docker-image-job.yml
        parameters:
          dockerImageName: ${{ parameters.dockerImageName}}
          containerRegistryName: ${{ parameters.containerRegistryName }}
          containerRegistryUrl: ${{ parameters.containerRegistryUrl }}
          artifactName: "${{ parameters.artifactName }}"
          artifactZipName: ${{ parameters.artifactZipName }}
          dockerImageFileName: ${{ parameters.dockerImageFileName }}

  - stage: updateHelmConfig
    displayName: Update Helm Config Repository
    dependsOn:
      - docker_publish
    jobs:
      - job: updateHelmConfigJob
        pool:
          name: Default
        workspace:
          clean: all
        steps:
          - template: ../../step_collections/process-cicd-script/v1.yml
            parameters:
              repositoryResource: ${{ parameters.helmfileRepoName }}
              branchName: $(Build.SourceBranch)
              tagsCollection: ${{ parameters.imageTagVariableName }}=$(build.buildnumber)
              commitMessage: Updated ${{ parameters.imageTagVariableName }} to $(build.buildnumber)
