parameters:
  # Gitversion
  - name: gitVersionSpec
    type: string
    default: "6.0.x"

  # BFF API Build Parameters
  - name: publishProject
    type: string
  - name: buildProject
    type: string
  - name: netCoreVersion
    type: string
    default: "6.0.x"
  - name: buildConfiguration
    type: string
    default: Release
  - name: externalFeedCredentials
    type: string
    default: "SpydersoftDevelop"

  # BFF API Test Settings
  - name: bffExecuteTests
    type: boolean
    default: false
  - name: bffTestProjects
    type: string
    default: "**/*tests/*.csproj"

  # BFF API Sonarqube Settings
  - name: bffExecuteSonar
    type: boolean
    default: false
  - name: bffSonarEndpointName
    type: string
  - name: bffSonarProjectKey
    type: string
  - name: bffSonarProjectName
    type: string
    default: ""
  - name: bffUseSonarCloud
    type: boolean
    default: false
  - name: bffSonarCloudOrganization
    type: string
    default: ""
  - name: bffSonarExtraProperties
    type: string
    default: ""

  # UI Build
  - name: uiSourceDirectory
    type: string
    default: "src/ui"
  - name: uiCodeCoverageFile
    type: string
    default: "output/coverage/cobertura-coverage.xml"
  - name: uiUnitTestFile
    type: string
    default: "output/test/junit.xml"

  # UI Sonarqube Settings
  - name: uiExecuteSonar
    type: boolean
    default: false
  - name: uiSonarEndpointName
    type: string
  - name: uiUseSonarCloud
    type: boolean
    default: false
  - name: uiSonarCloudOrganization
    type: string
    default: ""
  - name: uiSonarConfigFile
    type: string
    default: "sonar-project.properties"

  # Build Artifact Settings
  - name: artifactName
    type: string

  # Docker Settings
  - name: buildAndPublishDockerImage
    type: boolean
    default: false
  - name: artifactZipName
    type: string
  - name: dockerImageName
    type: string
  - name: imageTagVariableName
    type: string
  - name: containerRegistryName
    type: string
    default: proget_docker
  - name: dockerFilePath
    type: string
    default: $(Build.SourcesDirectory)/Dockerfile.simple

  # Helmfile Config Settings
  - name: updateHelmConfig
    type: boolean
    default: false
  - name: helmfileRepoName
    type: string

  # Hooks
  - name: prebuildSteps
    type: stepList
    default: []
  - name: preTestSteps
    type: stepList
    default: []

variables:
  - name: DOCKER_BUILDKIT
    value: 1

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        workspace:
          clean: all
        pool:
          name: Default
          demands: agent.os -equals Linux
        steps:
          - checkout: self
            fetchDepth: 0
            clean: true
          - task: UseDotNet@2
            displayName: "Use .NET Core sdk"
            inputs:
              packageType: sdk
              version: ${{ parameters.netCoreVersion }}
          - task: gitversion/setup@3
            displayName: Setup GitVersion on Agent
            inputs:
              versionSpec: ${{ parameters.gitVersionSpec }}
          - task: gitversion/execute@3
            displayName: Execute GitVersion to update build number

          - template: ../../step_collections/yarn-build-test/v1.yml
            parameters:
              nodeVersion: "21.4.0"
              zipBuildArtifacts: false
              workingDir: ${{ parameters.uiSourceDirectory }}
              useYarn2: true
              executeSonar: ${{ parameters.uiExecuteSonar }}
              sonarEndpointName: ${{ parameters.uiSonarEndpointName }}
              useSonarCloud: ${{ parameters.uiUseSonarCloud }}
              sonarCloudOrganization: ${{ parameters.uiSonarCloudOrganization }}
              sonar_config_file: ${{ parameters.uiSonarConfigFile }}
              codeCoverageFile: ${{ parameters.uiCodeCoverageFile }}
              unitTestFile: ${{ parameters.uiUnitTestFile }}

          - template: ../../step_collections/dotnet-api-build-steps/v1.yml
            parameters:
              buildProject: ${{ parameters.buildProject }}
              publishProject: ${{ parameters.publishProject }}
              netCoreVersion: ${{ parameters.netCoreVersion }}
              buildConfiguration: ${{ parameters.buildConfiguration }}
              externalFeedCredentials: ${{ parameters.externalFeedCredentials }}
              prebuildSteps: ${{ parameters.prebuildSteps }}
              preTestSteps: ${{ parameters.preTestSteps }}
              executeSonar: ${{ parameters.bffExecuteSonar }}
              sonarEndpointName: ${{ parameters.bffSonarEndpointName }}
              sonarProjectKey: ${{ parameters.bffSonarProjectKey }}
              sonarProjectName: ${{ parameters.bffSonarProjectName }}
              executeTests: ${{ parameters.bffExecuteTests }}
              testProjects: ${{ parameters.bffTestProjects }}
              useSonarCloud: ${{ parameters.bffUseSonarCloud }}
              sonarCloudOrganization: ${{ parameters.bffSonarCloudOrganization }}
              sonarExtraProperties: ${{ parameters.bffSonarExtraProperties }}

          # this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your pipeline.
          - publish: "$(Build.ArtifactStagingDirectory)"
            artifact: "${{ parameters.artifactName }}"

  - ${{ if eq(parameters.buildAndPublishDockerImage, true) }}:
      - stage: docker_publish
        displayName: Create Docker Image
        jobs:
          - template: ../../jobs/build-docker-image/v1.yml
            parameters:
              dockerImageName: ${{ parameters.dockerImageName}}
              containerRegistryName: ${{ parameters.containerRegistryName }}
              artifactName: "${{ parameters.artifactName }}"
              artifactZipName: ${{ parameters.artifactZipName }}
              dockerFilePath: "${{ parameters.dockerFilePath }}"

  - ${{ if eq(parameters.updateHelmConfig, true) }}:
      - stage: updateHelmConfig
        displayName: Update Helm Config Repository
        dependsOn:
          - docker_publish
        jobs:
          - job: updateHelmConfigJob
            pool:
              name: Default
            workspace:
              clean: all
            steps:
              - template: ../../step_collections/process-cicd-script/v1.yml
                parameters:
                  repositoryResource: ${{ parameters.helmfileRepoName }}
                  branchName: $(Build.SourceBranch)
                  tagsCollection: ${{ parameters.imageTagVariableName }}=$(build.buildnumber)
                  commitMessage: Updated ${{ parameters.imageTagVariableName }} to $(build.buildnumber)
